https://www.perplexity.ai/search/66a9bb20-44c6-46c5-93f4-bc92820868a3

In [1]:
import yfinance as yf
import pandas as pd

from pandas import DataFrame
start_date = '2024-01-01'
end_date = '2025-01-01'

tickers = ['2330.TW', '2303.TW', '2454.TW', '2317.TW']
all_data:dict[str:DataFrame]= {ticker: yf.download(ticker,start=start_date, end=end_date, interval='1d',auto_adjust=False) for ticker in tickers }
price_df = pd.DataFrame({key:dataframe['Adj Close'][key] for key,dataframe in all_data.items()})
price_df1 = price_df.rename(columns={'2330.TW':'台積電','2303.TW':'聯電','2454.TW':'聯發科','2317.TW':'鴻海'})
price_df1

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

                    台積電         聯電          聯發科          鴻海
Date
2024-01-02   585.720886  46.182152   898.152893   98.787247
2024-01-03   570.905090  45.025372   872.517517   98.316833
2024-01-04   572.880493  45.203339   872.141602   97.846420
2024-01-05   568.929565  45.203339   865.562927   97.846420
2024-01-08   575.843689  44.936390   864.623108   95.494339
...                 ...        ...          ...         ...
2024-12-25  1085.000000  41.378731  1354.439941  179.964066
2024-12-26  1085.000000  41.049957  1364.046021  180.929031
2024-12-27  1090.000000  40.956017  1373.651978  179.964066
2024-12-30  1090.000000  40.486340  1364.046021  178.516632
2024-12-31  1075.000000  40.439373  1359.243042  177.551682

[242 rows x 4 columns]

In [2]:
price_df2 = price_df1.groupby(price_df1.index.month).agg([("平均","mean"),("最高","max"),("最低","min")])
price_df2.index = "2024- "+ price_df2.index.astype(str) + "月份"
price_df2

                    台積電                                   聯電             \
                     平均           最高           最低         平均         最高
Date
2024- 1月份    596.945063   640.045776   568.929565  44.643150  46.538078
2024- 2月份    669.373638   689.432068   620.291260  43.286782  43.824104
2024- 3月份    754.910560   778.984680   680.542542  45.796558  47.427914
2024- 4月份    781.912094   813.716492   736.314209  45.283423  47.338928
2024- 5月份    822.241569   868.295044   766.084290  47.504761  50.364349
2024- 6月份    916.924374   977.245300   832.570923  49.746152  51.343163
2024- 7月份    992.235357  1075.866455   920.463501  49.499701  51.946510
2024- 8月份    932.598683   969.275940   811.880676  51.141651  52.604061
2024- 9月份    943.873541  1011.115173   885.597473  50.960184  52.040447
2024- 10月份  1036.753530  1080.847290   968.279785  48.045702  50.443539
2024- 11月份  1031.797639  1085.828125   992.187927  42.595423  44.290741
2024- 12月份  1068.751115  1090.000000  1031.038696  40.695561  42.083248

                               聯發科                                    鴻海  \
                   最低           平均           最高           最低          平均
Date
2024- 1月份   42.800797   870.564309   907.854309   826.091003   95.490065
2024- 2月份   42.711815   951.085430  1071.380737   874.021240   96.616102
2024- 3月份   42.978764  1095.323533  1155.963501  1038.487549  119.933544
2024- 4月份   43.334698  1013.535669  1127.769287   907.854309  142.441806
2024- 5月份   44.758423  1091.244959  1231.148193   939.807739  160.839326
2024- 6月份   47.605877  1281.600978  1409.711548  1155.963501  184.229553
2024- 7月份   46.967911  1280.037766  1402.469849  1171.926880  201.565271
2024- 8月份   46.920944  1132.018488  1205.547729   951.950439  174.042756
2024- 9月份   50.067795  1114.771399  1219.956543  1061.458374  173.257634
2024- 10月份  45.230099  1231.332128  1282.395264  1162.320923  198.247422
2024- 11月份  40.909050  1224.988351  1258.380493  1186.335815  200.779522
2024- 12月份  38.936401  1324.748907  1373.651978  1253.577515  182.179078


                    最高          最低
Date
2024- 1月份    98.787247   92.765930
2024- 2月份    97.376007   95.023926
2024- 3月份   146.299210   95.964760
2024- 4月份   149.592133  132.657166
2024- 5月份   174.524139  144.887970
2024- 6月份   204.630722  160.882095
2024- 7月份   218.562256  185.271317
2024- 8月份   195.403351  157.770111
2024- 9月份   184.306366  163.077362
2024- 10月份  208.430237  180.446548
2024- 11月份  212.290054  188.648666
2024- 12月份  193.955917  174.656815